name: JitPack Build Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  jitpack-build-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Test JitPack build commands
      run: |
        echo "Testing JitPack build process..."
        ./gradlew clean
        ./gradlew build publishToMavenLocal -x test
        
    - name: Verify artifacts
      run: |
        echo "Checking generated artifacts..."
        ls -la build/libs/
        echo "Sources jar:"
        ls -la build/libs/*-sources.jar || echo "Sources jar not found"
        echo "Javadoc jar:"
        ls -la build/libs/*-javadoc.jar || echo "Javadoc jar not found"
        
    - name: Test JitPack simulation
      run: |
        echo "Simulating JitPack build environment..."
        export SPRING_BOOT_JAR_ENABLED=false
        ./gradlew clean build publishToMavenLocal -x test
        
    - name: Upload JitPack test artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jitpack-test-artifacts
        path: |
          build/libs/*.jar
          ~/.m2/repository/com/utility/blockchain-relay-utility/
        retention-days: 1